### ISSUE TITLE
how to edit the host ip address?

### ISSUE THREAD

**Issue by dnelband** [seanjs-stack/seanjs#6]
currently im able to connect to the app only with localhost, i understand i need to change the ip from 127.0.0.1 to 0.0.0.0 but im having difficulties understanding where do i change this. so how could i change the app url ?

**Comment by Massad** [comment]
@dnelband you can't change the host from express or node, but you add an alias in the **hosts** file. For example `127.0.0.1 local.website.com`

Search for **change the hosts file windows/mac**
