### ISSUE TITLE
Heroku deploy - "User is not logged in" after sign in 

### ISSUE THREAD

**Issue by Promnovatsia** [seanjs-stack/seanjs#7]
I'm trying to deploy SEAN to heroku.

Redis ACL Backend failed to work. As i can see in the last commit it is not a local issue.

I forked SEAN with memory backend and deploy fresh build to [thomas-cookbook.herokuapp.com](https://thomas-cookbook.herokuapp.com).
I get signin response and immediately redirected back to the sign in form like was never authorized.

![image](https://cloud.githubusercontent.com/assets/20090247/16484093/1a89e350-3ec0-11e6-8efb-d3a6c16c2303.png)

> angular.js:9893 GET https://  thomas-cookbook.herokuapp.com/api/user 401 (Unauthorized)

But i can see [seanjs.herokuapp.com](http://seanjs.herokuapp.com/) version deployed and working normally.
What can be wrong with  [my repo](https://github.com/Promnovatsia/temp-github-cookbook)?
Everything works locally.

**Comment by Massad** [comment]
I checked [thomas-cookbook.herokuapp.com](http://thomas-cookbook.herokuapp.co) and it seems that you have issues with Redis connection as the Redis is used for storing the sessions.

[https://github.com/Promnovatsia/temp-github-cookbook/blob/master/config/lib/express.js#L153](https://github.com/Promnovatsia/temp-github-cookbook/blob/master/config/lib/express.js#L153)

Try to connect correctly to Redis.

**Comment by Promnovatsia** [comment]
Thanks. That resolved it.
I have local configs with ENV REDIS_HOST etc. but Heroku Redis provided only REDIS_URL.
After i set it in config explicitly it is started to work as intended.

I have a question about commit that switched to memory backend for module's policy.
What the issue? Why it is required to replace redis backend for acl?

**Comment by Massad** [comment]
Because someone tried to deploy it on Heroku and it didn't work because of it. I commented the Redis config so you have the option for Redis or memory; inside the policy.
